### ISSUE TITLE
README example failed

### ISSUE THREAD

**Issue by brianbruggeman** [mrk-its/bevy_webgl2#27]
I think the documentation should also include:

```shell
$ cargo install wasm-bindgen-cli
$ cargo install basic-http-server
```

Additionally, I think that the script should explicitly set CARGO_TARGET_DIR if it's not set:

```shell
$ CARGO_TARGET_DIR=`pwd`/target cargo make example sprite --profile release
```

Finally, I think a screenshot of a working version would be handy so I know what to expect.  Given no explicit debug information, it seems like this is just dead on arrival for me.

# Reproducible Steps:

1.  Uninstall wasm-bindgen
2. Uninstall basic-http-server
3. Unset CARGO_TARGET_DIR

4.  Then follow along below

Followed along with:

```shell
cargo install cargo-make
rustup target add wasm32-unknown-unknown
cargo make example sprite --profile release
```

And it failed with:
```shell
[cargo-make] INFO - Execute Command: "wasm-bindgen" "--remove-name-section" "--remove-producers-section" "--out-dir" "target" "--out-name" "wasm" "--target" "web" "--no-typescript" "${CARGO_TARGET_DIR}/wasm32-unknown-unknown/release/examples/sprite.wasm"
[cargo-make] ERROR - Error while executing command, error: Os {
    code: 2,
    kind: NotFound,
    message: "No such file or directory",
}
[cargo-make] WARN - Build Failed.
```

So just to make sure, I ran:

```shell
wasm-bindgen --remove-name-section --remove-producers-section --out-dir target --out-name wasm --target web --no-typescript target/wasm32-unknown-unknown/release/examples/sprite.wasm 
zsh: command not found: wasm-bindgen
```

Assumption here is that there's a step missing to install `wasm-bindgen`.

Googling, it sounds like I could just install [wasm-bindgen-cli](https://github.com/rustwasm/wasm-bindgen/tree/master/crates/cli): 

```shell
cargo install wasm-bindgen-cli
```

Once it's installed, the `wasm-bindgen` command above passed.  However, I needed to explicitly add `CARGO_TARGET_DIR` to my environment:

```shell
CARGO_TARGET_DIR=`pwd`/target cargo make example sprite --profile release
```

The next blocker was lacking [basic-http-server](https://github.com/brson/basic-http-server).  This was resolved with `cargo install basic-http-server`.

After installing and setting up, I was greeted with an empty page.  I'm not sure what I should be expecting.

**Comment by mrk-its** [comment]
Thanks for very detailed description and reproducible steps, it was very helpful.
I've just pushed fixes, let me know if it works for you.

**Comment by brianbruggeman** [comment]
This definitely improves the ergonomics of the installation process. Thank you!

However, I still have a problem on a Mac when I run.

I may have a poor assumption here.  Please let me know.

I think that regardless of the platform I compile on (mac, linux, windows), the WASM output should be the same.  I can access the examples page without an issue on my mac.  But when I compile on my mac, the WASM target has promise errors that prevent it from running.  The stack trace makes it non-trivial to understand what's really going on.

If I compile on Windows, then the WASM runs flawlessly.
